version: '3'

services: 
    frontend:
        build: ./frontend
        container_name: DOCKER-TUTORIAL-FRONTEND
        command: serve -s build -l 3000
        restart: unless-stopped
        networks:
            - docker-tutorial-network
    api:
        build: ./api
        container_name: DOCKER-TUTORIAL-API
        command: npm run start
        restart: unless-stopped
        ports: 
            - "3001:3001"
        environment: 
            - PORT=3001
            - HOST=http://npolyakoff.com
            - MONGO_URL=mongodb://api_db:27017/api
            - AUTH_API_URL=http://auth:3002/api
        depends_on: 
            - api_db
        networks:
            - docker-tutorial-network
    auth:
        build: ./auth
        container_name: DOCKER-TUTORIAL-AUTH
        command: npm run start
        restart: unless-stopped
        ports: 
            - "3002:3002"
        environment: 
            - PORT=3002
            - HOST=http://npolyakoff.com
            - MONGO_URL=mongodb://auth_db:27017/auth
            - API_URL=http://api:3001/api

        depends_on: 
            - auth_db
        networks:
            - docker-tutorial-network
    api_db:
        container_name: DOCKER-TUTORIAL-API_DB
        image: mongo:latest
        volumes: 
            - mongodb_api:/data/db
        networks:
            - docker-tutorial-network
    auth_db:
        container_name: DOCKER-TUTORIAL-AUTH_DB
        image: mongo:latest
        volumes: 
            - mongodb_auth:/data/db
        networks:
            - docker-tutorial-network
    nginx:
        image: nginx:stable-alpine
        container_name: DOCKER-TUTORIAL-NGINX
        ports:
            - "80:80"
        volumes: 
            - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
        depends_on: 
            - frontend
        networks:
            - docker-tutorial-network
        
volumes: 
    mongodb_api:
    mongodb_auth:

networks:
    docker-tutorial-network:
        driver: bridge
