version: '3'

services: 
    api:
        command: npm run dev
        volumes: 
            - ./api/src:/usr/src/app/src
    auth:
        command: npm run dev
        volumes: 
            - ./auth/src:/usr/src/app/src